/**
 * Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: help@itsallsavvy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { CustomerId } from './customerId';


export interface Customer { 
    id?: string;
    version?: number;
    deleted?: boolean;
    createdBy?: string;
    createdDate?: string;
    lastModifiedUser?: string;
    lastModifiedDate?: string;
    ownerId: string;
    userId?: string;
    companyName?: string;
    companyNumber?: string;
    address?: Address;
    customerSource?: string;
    externalCustomerId?: string;
    customerId?: CustomerId;
}

